tap "tmuxpack/tpack"
brew "fish"
brew "fisher"
brew "fzf"
brew "git"
brew "mise"
brew "tree-sitter"
brew "neovim"
brew "readline"
brew "ripgrep"
brew "tmux"
brew "tree-sitter-cli"
cask "1password-cli"
cask "font-meslo-lg-nerd-font"
cask "tmuxpack/tpack/tpack", trusted: true
cask "wezterm"
